-- Migration updates for Achievements and Study Materials

ALTER TABLE ONLY achievements 
  ADD COLUMN IF NOT EXISTS rank VARCHAR(100),
  ADD COLUMN IF NOT EXISTS name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS camp_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS college_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS camp_photos TEXT[],
  ADD COLUMN IF NOT EXISTS is_approved BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_special BOOLEAN DEFAULT FALSE;

ALTER TABLE ONLY achievements ALTER COLUMN cadet_id DROP NOT NULL;

ALTER TABLE ONLY study_materials 
  ADD COLUMN IF NOT EXISTS drive_link VARCHAR(500);

ALTER TABLE ONLY study_materials ALTER COLUMN file_url DROP NOT NULL;
ALTER TABLE ONLY study_materials ALTER COLUMN file_name DROP NOT NULL;

